### ISSUE TITLE
朋友你好，想请教一下关于你的个人博客的一些小问题

### ISSUE THREAD

**Issue by gavincoder-china** [zhangjaycee/vector_quantization_lbg#1]
①你的博客ui很好看，我也想搞一个，你是用的什么模板呢？
②你的博客里面代码显示区很好看，markdown编译器是博客模板自带的吗？

**Comment by zhangjaycee** [comment]
你好，不知道你为什么在这里问问题。
我用的wordpress搭建的，主题是免费的，叫Flat，wordpress后台可以安装。
代码显示的插件也可以在wordpress后台搜到和安装，叫Crayon Syntax Highlighter。
markdown解释器需要安装wordpress官方的一个插件，叫Jetpack。
